# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(choices=[('SK', 'Skiing'), ('RU', 'Running'), ('CY', 'Cycling')], default='RU', max_length=2)),
                ('time', models.TimeField()),
                ('distance', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
