# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 10:54
from __future__ import unicode_literals

import distances.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('distances', '0002_auto_20170421_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exercise',
            name='distance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='hours',
            field=distances.fields.IntegerRangeField(default=0),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='minutes',
            field=distances.fields.IntegerRangeField(default=0),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='sport',
            field=models.CharField(choices=[('Skiing', 'Skiing'), ('Running', 'Running'), ('Cycling', 'Cycling')], default='Running', max_length=20),
        ),
    ]
