# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 11:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distances', '0004_auto_20170428_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
