# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 12:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distances', '0005_auto_20170429_1455'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={},
        ),
    ]
