# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distances', '0006_auto_20170429_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='sport',
            field=models.CharField(choices=[('Running', 'Running'), ('Skiing', 'Skiing'), ('Cycling', 'Cycling'), ('Walking', 'Walking'), ('Swimming', 'Swimming')], default='Running', max_length=20),
        ),
    ]
