# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 09:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distances', '0007_auto_20170508_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField(default=datetime.datetime(2017, 5, 4, 12, 59, 51, 221329))),
                ('endDate', models.DateField(default=datetime.datetime.now)),
            ],
        ),
        migrations.AlterField(
            model_name='exercise',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
