# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 14:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distances', '0008_auto_20170511_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='text',
            field=models.CharField(default='description', max_length=300),
        ),
        migrations.AlterField(
            model_name='dates',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2017, 5, 5, 17, 36, 6, 917070)),
        ),
    ]
