# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-10 11:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distances', '0011_auto_20170602_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='sub_sport',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='dates',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2017, 6, 3, 14, 13, 55, 386022)),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='sport',
            field=models.CharField(choices=[('Running', 'Running'), ('Skiing', 'Skiing'), ('Cycling', 'Cycling'), ('Walking', 'Walking'), ('Swimming', 'Swimming'), ('Other', 'Other')], default='Running', max_length=20),
        ),
    ]
