# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-10 12:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distances', '0012_auto_20170610_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dates',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2017, 6, 3, 15, 22, 27, 931413)),
        ),
    ]
