# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-13 08:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distances', '0013_auto_20170610_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='tags',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='dates',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2017, 6, 6, 11, 52, 18, 360967)),
        ),
    ]
