# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-13 09:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distances', '0014_auto_20170613_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dates',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2017, 6, 6, 12, 47, 32, 505195)),
        ),
    ]
