# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-26 14:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distances', '0015_auto_20170613_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dates',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2017, 6, 19, 17, 58, 28, 727598)),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='text',
            field=models.CharField(default='', max_length=300),
        ),
    ]
