# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-08 09:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distances', '0016_auto_20170626_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dates',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2017, 7, 1, 12, 20, 26, 96390)),
        ),
    ]
