# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-09 11:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distances', '0017_auto_20170708_1220'),
        ('distances', '0017_auto_20170708_0912'),
    ]

    operations = [
    ]
