# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-09 12:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distances', '0018_merge_20170709_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dates',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2017, 7, 2, 15, 14, 20, 491488)),
        ),
    ]
