# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-14 11:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distances', '0021_auto_20170714_1141'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dates',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
