# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-17 10:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distances', '0022_auto_20170714_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='testtime',
            field=models.TimeField(blank=True, default=datetime.time(0, 0)),
        ),
    ]
