# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-21 13:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distances', '0023_exercise_testtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='testtime',
        ),
    ]
